name: Ruby Setup and Version Check

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: blacksmith-staging
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Ruby
      uses: useblacksmith/setup-ruby@v2
      with:
        ruby-version: 3.4.2
    
    - name: Verify Ruby version
      run: |
        installed_version=$(ruby -v | cut -d' ' -f2)
        if [ "$installed_version" = "3.4.2" ]; then
          echo "Ruby version is correct: $installed_version"
        else
          echo "Ruby version is incorrect. Expected 3.4.2, but got $installed_version"
          exit 1
        fi
